version: "3"

services:
  etracs-server:
    volumes:
      ## this is only a seed mapping, please do not remove
      ##
      - ../../_custom/.emptydir:/.emptydir

      ## mounted RPTIS services build 2.5.04.05.02
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar

      - ./dev_modules/admin:/services/modules/admin
      - ./dev_modules/bpls:/services/modules/bpls
      - ./dev_modules/jasper:/services/modules/jasper
      - ./dev_modules/treasury:/services/modules/treasury
